# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-11 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComentariosFarmacia',
            new_name='ComentarioFarmacia',
        ),
    ]
