# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-19 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181018_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariofarmacia',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
